version: "3"

services:
  nginx:
    image: todo-list-api_nginx
    ports:
      - "80:80"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TO_DO_LIST
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    image: todo-list-api_backend
    depends_on:
      - db
    # ports:
    #   - '3001:3001'
  frontend:
    image: todo-list-api_frontend
    # ports:
    #   - '3000:3000'